import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col">
          <header className="fixed w-full">
            <Navbar />
          </header>
          <div className="flex flex-col h-screen">
            <div className="flex flex-row">
              <div className="flex-1">
                <Sidebar />
              </div>
              <main className="flex-5 scroll-smooth overflow-y-auto p-5">
                <div className="p-5 w-full md:max-w-[1140px]">{children}</div>
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
